{{- if .Values.services.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-to-running.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zero-to-running.labels" . | nindent 4 }}
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.backend.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: backend
    {{- include "zero-to-running.selectorLabels" . | nindent 4 }}
{{- end }}

