{{- if .Values.services.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-to-running.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zero-to-running.labels" . | nindent 4 }}
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: {{ .Values.services.frontend.port }}
    protocol: TCP
    name: http
  selector:
    app: frontend
    {{- include "zero-to-running.selectorLabels" . | nindent 4 }}
{{- end }}

